# loop

# 1. for loop

name = "rishabh"

for i in name:
    print(i)


color = ["red", "blue", "green"]
for colors in color:
    print(colors)


# range() {What if we do not want to iterate over a sequence? What if we want to use for loop for a specific number of times?}

# for k in range(1, 2):
#     print(k+1)

for k in range(1, 50, 20):
    print(k)
# {This creates a range of numbers starting from 1 (inclusive), up to but not including 50, with a step size of 20. So, the sequence generated by this range is 1, 21, and 41.}


# 2. While loop {As the name suggests, while loops execute statements while the condition is True. As soon as the condition becomes False, the interpreter comes out of the while loop.}

i = 0
while (i < 3):
    print(i)

    i = i+1


# Else with While Loop

x = 5
while (x > 0):
    print(x)
    x = x - 1
else:
    print('counter is 0')

# Do-While loop in python{do..while is a loop in which a set of instructions will execute at least once (irrespective of the condition) and then the repetition of loop's body will depend on the condition passed at the end of the while loop. It is also known as an exit-controlled loop.}

while True:
    number = int(input("Enter a positive number: "))
    print(number)
    if not number > 0:
        break
